#
# Makefile for the Goodix gt9xx touchscreen driver.
#
#subdir-ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_GT9XX_PD1510_DRIVER)	+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_PD1510_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_PD1510_DEBUG)	+= goodix_tool.o
